#!/bin/bash
(osqueryi --list --separator ',' |
    cut -c 1-300 |
    column -t -s ',' |
    sed '1d') <<EOF
SELECT s.pid, s.local_port, p.cmdline, p.cwd
FROM process_open_sockets AS s
INNER JOIN processes AS p
ON s.pid = p.pid
ORDER BY p.cmdline;
EOF
