#!/usr/bin/python3
import os
import sys
from typing import Iterable, TypeVar


def print_toggled_features(prefix: str):
    toggleable = {"line-numbers", "side-by-side"}
    feature = only(opt for opt in toggleable if opt.startswith(prefix))
    features = os.getenv("DELTA_FEATURES") or "+"
    assert features and features.startswith("+")
    features = set(filter(bool, features[1:].split(",")))
    if feature in features:
        features.remove(feature)
    else:
        features.add(feature)
    print("+" + ",".join(sorted(features)))


T = TypeVar("T")


def only(it: Iterable[T]) -> T:
    it = iter(it)
    try:
        t = next(it)
    except StopIteration:
        raise ValueError("Iterable is empty")
    try:
        next(it)
        raise ValueError("Iterable had more than one item")
    except StopIteration:
        return t


if __name__ == "__main__":
    try:
        [prefix] = sys.argv[1:]
    except ValueError:
        print(os.getenv("DELTA_FEATURES"))
        exit(0)
    else:
        print_toggled_features(prefix)
