#!/usr/bin/env python
import codecs
import json
import sys

try:
    from rich import print as rprint
    from rich.console import Console
    from rich.syntax import Syntax
except ImportError:
    sys.stderr.write("Please install rich: `pip install rich`\n")
    sys.exit(1)

console = Console()


def main():
    for line in sys.stdin:
        try:
            brace = line.index("{")
            record = json.loads(line[brace:])
            if not isinstance(record, dict):
                raise ValueError
            prefix = line[:brace]
            if prefix:
                record["_prefix"] = prefix
            console.print(style_record(transform(record)))
        except:
            try:
                rprint(line, end="")
            except:
                print(line, end="")


def transform(record: dict) -> dict:
    for k in ["stacktrace"]:
        try:
            v = record[k]
            if isinstance(v, str):
                v = format_string(v)
            if isinstance(v, list):
                v = list(map(format_string, v))
            record[k] = v
        except:
            pass
    return record


def format_string(s: str) -> str:
    try:
        return codecs.decode(s, "unicode_escape")
    except:
        return s


def style_record(record: dict) -> Syntax:
    is_error = "error" in record or "stacktrace" in record
    error_theme = "default"  # happens to apply red style to strings
    s = json.dumps(record, indent=2).replace("\\n", "\n").replace("\\t", "\t")
    # default, sas, manni
    return Syntax(s, "json", theme=error_theme if is_error else "sas", word_wrap=True)


main()
