#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.9"
# dependencies = ["typer"]
# ///

import random
from pathlib import Path
from typing import Iterable, Iterator

import typer  # type: ignore

app = typer.Typer()


@app.callback(invoke_without_command=True)
def callback(ctx: typer.Context):
    if ctx.invoked_subcommand is None:
        raise typer.Exit(ctx.get_help())


WORDS_FILE = Path(__file__).resolve().parent / "typing-practice-words.txt"


def ngrams_from_word(word: str, n: int, letters: str) -> Iterator[str]:
    _letters = set(letters)
    L = len(word)
    if L >= n:
        for i in range(0, L - n + 1):
            ng = word[i : i + n]
            if set(ng) <= _letters:
                yield ng


def ngrams_from_words(words: list[str], n: int, letters: str) -> Iterator[str]:
    for word in words:
        yield from ngrams_from_word(word, n, letters)


def coalesce(
    words: Iterable[tuple[str, ...]], word_length: int, repeat: int
) -> Iterable[str]:
    output_word = ""
    for _chunk in words:
        chunk = "".join(_chunk)
        for _ in range(repeat):
            output_word += chunk
            if len(output_word) >= word_length:
                yield output_word
                output_word = ""


def coalesced_ngrams(
    letters: str, ngram_length: int, word_length: int = 6, repeat: int = 1
):
    ngrams = list(ngrams_from_words(get_words(), ngram_length, letters))
    ngrams = random.choices(ngrams, k=1000)
    for w in coalesce(zip(ngrams, ngrams[1:]), word_length, repeat):
        print(w, end=" ")


def get_words(k=1000) -> list[str]:
    return WORDS_FILE.read_text().splitlines()[:k]


@app.command()
def ngrams(
    letters: str = "asertdloniuy",
    ngram_length: int = 2,
    word_length: int = 6,
    repeat: int = 4,
    hard: bool = False,
):
    if hard:
        for _ in range(100):
            for w in HARD_WORDS:
                print(w, end=" ")
    else:
        coalesced_ngrams(letters, ngram_length, word_length, repeat)


HARD_WORDS = ["dsatdsat", "ssadssad", "adetadet"]


@app.command()
def words(repeat: int = 1):
    for w in random.choices(get_words(), k=100):
        for _ in range(repeat):
            print(w, end=" ")


if __name__ == "__main__":
    import signal

    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    app()
