#!/bin/bash
if [ -n "$1" ]; then
    next_window="$1"
else
    next_window="$(
        tmux list-panes -a -F '#{session_name},#{window_index},#{pane_title}' |
            xsv table |
            fzf --exact |
            awk '{print $1":"$2}'
    )"
fi
tmux display-message -p -F '#{session_name}:#{window_index}' >/tmp/tmux-last-window
tmux switch-client -t "$next_window"
