#!/bin/bash
set -e

die() {
    echo "$1" 1>&2
    exit 1
}
rel_path="$1"
[ -f "$rel_path" ] && [ -x "$rel_path" ] || die "error: $rel_path is not an executable"
ln -s $(readlink -f "$rel_path") ~/bin/$2
