#!/bin/bash
set -e

die() {
    echo "$1" 1>&2
    exit 1
}
rel_path="$1"
[ -f "$rel_path" ] || die "error: $rel_path is not a file"
if [ ! -x "$rel_path" ]; then
    chmod +x "$rel_path"
fi
ln -fs $(readlink -f "$rel_path") ~/bin/"$2"
