#!/bin/bash

if [[ $1 == "rel"* ]]; then
    ln -fs /usr/local/bin/delta ~/bin/delta
elif [[ $1 == "dev" ]]; then
    ln -fs ~/src/delta/target/aarch64-apple-darwin/release/delta ~/bin/delta
else
    echo "usage: $(basename $0) [release|dev]" >&2
    exit 1
fi
echo "$(readlink -f ~/bin/delta) $(delta --version | ansifilter | sed -E 's,^delta ,,')"
