#!/bin/bash

RG="rg $@ --color=always"
BAT="bat --color=always --style=header"
DELTA="delta --grep-output-type classic"

fzf() {
    command fzf \
        --layout reverse \
        --info hidden \
        --preview-window='~1' \
        --prompt ' ' \
        --color light \
        --ansi \
        --bind 'ctrl-k:kill-line' \
        "$@"
}

declare preview="echo; $BAT -H {2} {1} | $RG -C10 {q}"

$RG --json . 2>/dev/null |
    $DELTA |
    fzf -d: \
        --query="${*}" \
        --phony \
        --bind="change:reload:$RG --json {q} | $DELTA" \
        --bind='enter:execute:code -g {1}:{2}' \
        --preview="[[ -n {1} ]] && $preview"
