#!/bin/bash

rg_args='-i'
if [ "$1" = "--exclude-tests" ]; then
    rg_args+=' -g "!*test*" -g "!*mock*" -g "!openapiv*"'
    shift
fi

RG="rg $rg_args --color=always"
DELTA="delta --light --grep-output-type classic"

fzf() {
    command fzf \
        --layout reverse \
        --info hidden \
        --prompt ' ' \
        --color light \
        --ansi \
        --bind 'ctrl-k:kill-line' \
        --bind 'alt-right:forward-word' \
        --bind 'alt-left:backward-word' \
        --preview-window 'up,70%' \
        --history /tmp/fzf-rg.history \
        "$@"
}

$RG --json . $1 2>/dev/null |
    $DELTA |
    fzf -d: \
        --query="${*}" \
        --phony \
        --bind="change:reload:$RG --json {q} $1 | $DELTA" \
        --bind='enter:execute:code -g {1}:{2}' \
        --preview="[[ -n {1} ]] && fzf-rg-preview {1} {2}"
