#!/bin/bash

most_recent_snapshot() {
    local current_branch=$(git rev-parse --abbrev-ref HEAD)
    local prefix="z-"
    local suffix_base="-"
    local latest_snapshot=$(git branch --list "$prefix$current_branch$suffix_base*" | sort -V | tail -n 1)

    echo "$latest_snapshot"
}

next_snapshot() {
    local current_branch=$(git rev-parse --abbrev-ref HEAD)
    local prefix="z-"
    local suffix_base="-"
    local n=1

    while git show-ref --verify --quiet refs/heads/"$prefix$current_branch$suffix_base$n"; do
        n=$((n + 1))
    done

    echo "$prefix$current_branch$suffix_base$n"
}

die() {
    echo "git snapshot [create|c]" 1>&2
    exit 1
}

if [[ "$1" == "--create" || "$1" == "-c" ]]; then
    new_branch=$(next_snapshot)
    git branch -c "$(git rev-parse --abbrev-ref HEAD)" "$new_branch"
    echo "Created branch: $new_branch"
elif [[ -n "$1" ]]; then
    die
else
    echo $(most_recent_snapshot)
fi
