#!/bin/bash

function hyperlink() {
    local url="$1"
    local text="$2"
    printf '\e]8;;%s\e\\%s\e]8;;\e\\\n' "$url" "$text"
}


if echo "$@" | rg -q '(^| )\-[^- ]*l[^-]+' || [[ "$*" == *" --files-with-matches "* ]]; then
    rg --hidden -g '!.git/*' "$@" | while read path; do
        abspath=$(readlink -f -- "$path")
        # Editor-agnostic: the wormhole daemon opens this in the current editor.
        url="http://wormhole:7117/file/$abspath?land-in=editor"
        hyperlink "$url" "$path"
    done
else
    rg --hidden -g '!.git/*' --json "$@" | delta
fi
