#!/bin/bash

function hyperlink() {
    local url="$1"
    local text="$2"
    printf '\e]8;;%s\e\\%s\e]8;;\e\\\n' "$url" "$text"
}

if [[ "$@" == *" -l "* ]] || [[ "$@" == *" --files-with-matches "* ]]; then
    rg --hidden -g '!.git/*' "$@" | while read path; do
        abspath=$(readlink -f -- $path)
        url="vscode://file/$abspath"
        hyperlink "$url" "$path"
    done
else
    if [[ -n "$RG_DELTA_HYPERLINK_KEYS" ]]; then
        osascript -e 'tell application "System Events" to tell process "Alacritty" to keystroke "." using command down'
    fi
    rg --hidden -g '!.git/*' --json -C 10 "$@" | delta
fi
