#!/bin/bash

# GPT4
function sg2rg() {
    jq -c '{
        type: "match",
        data: {
            path: { text: .file },
            lines: { text: .lines },
            line_number: (.range.start.line + 1),
            absolute_offset: .range.byteOffset.start,
            submatches: [{
            match: { text: .text },
            start: .range.start.column,
            end: .range.end.column
            }],
            language: .language
        }
    }'
}

# GPT4
function coalesce() {
    python -c "
import json
import sys

def combine_matches():
    combined = []
    last_line = None

    for line in sys.stdin:
        data = json.loads(line)

        if (last_line and 
                last_line['data']['path']['text'] == data['data']['path']['text'] and
                last_line['data']['line_number'] == data['data']['line_number']):
            last_line['data']['submatches'].extend(data['data']['submatches'])
        else:
            if last_line:
                combined.append(last_line)
            last_line = data

    if last_line:
        combined.append(last_line)

    return combined

for data in combine_matches():
    print(json.dumps(data))

"
}

command sg -C 3 --json=stream "$@" | sg2rg | coalesce | delta
