#!/bin/bash

close-project() {
    local project="$1"
    hs <<EOF
    for _, win in ipairs(hs.window.allWindows()) do
        local app = win:application()
        if app:name() == "Cursor" then
            local title = win:title()
            if title:match(" — $project\$") then
                print("Closing " .. title .. " isFullScreen: " .. tostring(win:isFullScreen()) .. " isMinimized: " .. tostring(win:isMinimized()))
                win:toggleFullScreen()
                win:toggleZoom()
                hs.timer.usleep(500000)
                print("Closing " .. title .. " isFullScreen: " .. tostring(win:isFullScreen()) .. " isMinimized: " .. tostring(win:isMinimized()))
                win:setFullScreen(false)  -- unmaximize first
                win:minimize()
                win:close()
            end
        end
    end
EOF
}

close-project "$1"
