#!/bin/bash

close-project() {
    local project="$1"
    osascript <<EOF
tell application "Cursor"
    repeat with w in windows
        if w's name ends with " — $project" then
            set miniaturized of w to true
            delay 0.1
            close w
        end if
    end repeat
end tell
EOF
}

close-project "$1"
