#!/bin/bash
commit="$1"
file="$2"
git show "$commit~1":"$file" >"/tmp/before-$(basename $file)"
git show "$commit":"$file" >"/tmp/after-$(basename $file)"
diff -u "/tmp/before-$(basename $file)" "/tmp/after-$(basename $file)"
