#!/usr/bin/python3

# http://localhost:8080/namespaces/default/workflows/7a66492eacdf4215a17dec4ec3b3a7a2/b8108716-1824-4b46-89d4-43d86774fd75/history

import os
import re
import sys

try:
    [verb, url] = sys.argv[1:]
except ValueError:
    from pathlib import Path

    print(f"usage {Path(__file__).name} <verb> <url>")

regex = r"^https?://(?P<hostname>[^:]+):(?P<port>\d+)/namespaces/(?P<namespace>[^/]+)/workflows/(?P<workflow_id>[^/]+)/(?P<run_id>[^/]+)"
m = re.match(regex, url)
assert m, f"No match: {regex}"
w = m.groupdict()
port = {"8080": "7233"}[w["port"]]
cmd = [
    "temporal",
    "workflow",
    verb,
    "--address",
    f"{w['hostname']}:{port}",
    "--namespace",
    w["namespace"],
    "--workflow-id",
    w["workflow_id"],
    "--run-id",
    w["run_id"],
]
print(" ".join(cmd), file=sys.stderr)
os.execvp("temporal", cmd)
